service: product-service

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

useDotenv: true

environment:
  PG_HOST: ${env:PG_HOST}
  PG_PORT: ${env:PG_PORT}
  PG_DB: ${env:PG_DB}
  PG_USER: ${env:PG_USER}
  PG_PASS: ${env:PG_PASS}

functions:
  getProduct:
    handler: src/getProductById.handler
    events:
      - http:
          path: /product/{id}
          cors: true
          method: get
  getProducts:
    handler: src/getProducts.handler
    events:
      - http:
          path: /product
          cors: true
          method: get
  postProduct:
    handler: src/postProducts.handler
    events:
      - http:
          path: /product
          cors: true
          method: post
