service: product-service

plugins:
  - serverless-webpack
  - serverless-offline

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

environment:
  PG_HOST: products.clbzxnessjuh.eu-west-1.rds.amazonaws.com
  PG_PORT: 5432
  PG_DB: products 
  PG_USER: postgres
  PG_PASS: ShvFNAexlCFcopXtsR8x

functions:
  getProduct:
    handler: src/getProductById.handler
    events:
      - http:
          path: /product/{id}
          cors: true
          method: get
  getProducts:
    handler: src/getProducts.handler
    events:
      - http:
          path: /product
          cors: true
          method: get
